use_frameworks!

target 'SwiftUIMetal (iOS)' do
    platform :ios, '11.0'
    pod 'iShapeTriangulation',            '1.0.0'
end

target 'SwiftUIMetal (macOS)' do
    platform :osx, '10.15'
    pod 'iShapeTriangulation',            '1.0.0'
end
